### ISSUE TITLE
Request for a release

### ISSUE THREAD

**Issue by raulraja** [macroing/CEL4J-Artifact#1]
Hi!, Is this lib still maintained? I'm in need of a decent ScriptEngine that supports generics unlike the beanshell one and I'd like to use this one if it works. Thanks!

**Comment by macroing** [comment]
Hi Raúl,

Thank you for your interest in my library!

This library is still maintained, but I havn't made any changes to it for quite some time. It should work though, as far as I know.

I think I will remove the dependency to my other library. That will make it easier for you and others to use it.

If you have any ideas for features and other improvements, I'm happy to listen. I might very well implement them.

**Comment by raulraja** [comment]
Awesome, is this released somewhere? We'd love to test it but currently I can't build from sources because of the other libs not linked in the repo.

**Comment by macroing** [comment]
It hasn't been released anywhere yet. But the other library can be found [here](https://github.com/macroing/CIT-Java).

I am actually removing the dependency as we speak. Hopefully I will finish that today.

**Comment by raulraja** [comment]
I'll wait for that then, thanks!

**Comment by macroing** [comment]
Now I've uploaded a beta release of it. The dependency is gone.

**Comment by raulraja** [comment]
Great!, Where has it been released?

**Comment by macroing** [comment]
You can find it on the release page. The built project is in a .zip file.

**Comment by raulraja** [comment]
Thanks I'll report back if I find any issues, cheers!

**Comment by Guardiola31337** [comment]
Hey @macroing 👋

> You can find it on the release page. The built project is in a .zip file.

I tried to include it in https://github.com/arrow-kt/ank adding `compile fileTree(dir: 'libs', include: ['*.jar'])` to `build.gradle` file but didn't work...

Anyways, after cloning your repo and generating/releasing the artifact locally and add the dependency as a regular one it worked smoothly 🎉
I can open a PR with everything setup to upload the artifact to Maven Central or Bintray. As you can imagine more convenient for users that want to consume _Artifact_. Would you be interested in this?

FWIW, generics are working 💯 ❤️

As mentioned before our idea is using _Artifact_ as ScriptEngine for the Java code in [ΛNK](https://github.com/arrow-kt/ank) but I saw that _Artifact_ is licensed under the `GNU General Public License v3.0` and ΛNK is licensed under the `Apache License 2.0` so now I'm wondering if there might be any kind of incompatibility between the licenses and therefore be an issue to ΛNK users. To avoid that, would you consider changing _Artifact_'s license to an Academic (e.g. `MIT`) or a Permissive (e.g. `Apache`) less restrictive license? What do you think?

Thanks for developing _Artifact_, it's awesome!

cc @raulraja

**Comment by macroing** [comment]
Hi @Guardiola31337,

Thank you for showing interest in my library!

I'd be more than happy to accept a pull request that adds support for Maven and / or other build tools. Because I've only used Maven a couple of times in the past, I skipped adding support for that myself.

The license is actually LGPL v3.0 and not GPL v3.0. I've noticed that some of my repositories show GPL v3.0, whereas others show LGPL v3.0. The same COPYING and COPYING.LESSER files have been included with all my repositories. Maybe the COPYING.LESSER file has been modified somehow when I've uploaded it to some of my repositories? Otherwise I don't know why.

I thought LGPL v3.0 would be permissive enough. But reading about it, it doesn't look like it. So I might as well just change the license to MIT, which seems the least restrictive.

You should note that I made some backwards-incompatible changes to the code of the scripting language itself, after the beta release. Mainly how import- and package statements are written. They no longer require a "#" character in front of them. I also deleted some minor features that weren't useful.

**Comment by Guardiola31337** [comment]
@macroing 
> I'd be more than happy to accept a pull request that adds support for Maven and / or other build tools. Because I've only used Maven a couple of times in the past, I skipped adding support for that myself.

There you go https://github.com/macroing/CEL4J-Artifact/pull/2 🚀

> So I might as well just change the license to MIT, which seems the least restrictive.

Thank you very much for changing the license 🙏

> You should note that I made some backwards-incompatible changes to the code of the scripting language itself, after the beta release. Mainly how import- and package statements are written. They no longer require a "#" character in front of them. I also deleted some minor features that weren't useful.

Will follow with some questions that showed up after testing _Artifact_ as ScriptEngine for the Java code in [ΛNK](https://github.com/arrow-kt/ank) locally.

Thanks again!
